### ISSUE TITLE
Getting this error in AppEngine logs, In many of the api calls

### ISSUE THREAD

**Issue by zonito** [cloudendpoints/endpoints-management-python#52] opened 2017-11-02 16:11 UTC
```python
/base/data/home/apps/s~app/v2.405240549392103317/lib/urllib3/contrib/appengine.py:115: AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets. To use sockets directly instead of URLFetch see https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html. AppEnginePlatformWarning)
```

This error is from the internal library and I am not interested to see this error then why it is highlighted as an error, please suppress it with a warning or fix the error.

Note:
- I am in the process of migrating endpoints v1 to v2.

**Comment by inklesspen** [comment] 2018-05-01 22:02
Dupe of #40.

**Closed by inklesspen** 2018-05-01 22:02 UTC
